# Generated by Django 3.2.4 on 2024-11-08 23:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0149_add_well_status_to_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquiferparameters',
            name='private',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False),
        )
    ]
