# Generated by Django 3.2.4 on 2024-11-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0150_auto_20241108_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellattachment',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
