# Auto Label Git Action Config
# 'label_name'
#   - path_of_diff/where/code_lives/to_base_label_upon

# Any change to any file in .github/workflows
'GitHub Actions':
  - changed-files:
    - any-glob-to-any-file: ['.github/workflows/*']

# Any change to the docker-compose file or any dockerfile in the repo
'Docker':
  - changed-files:
    - any-glob-to-any-file: ['**/Dockerfile', 'docker-compose.yml']
  
# Any changes to file or subfolders in /backend
'Backend':
  - changed-files:
    - any-glob-to-any-file: ['app/backend/**/*']
  
# Any changes to file or subfolders in /frontend
'Frontend':
  - changed-files:
    - any-glob-to-any-file: ['app/frontend/**/*']

# Any changes to file or subfolders in /database
'Database':
  - changed-files:
    - any-glob-to-any-file: ['app/database/**/*']

# Any changes to file or subfolders in /scripts
'Scripts':
  - changed-files:
    - any-glob-to-any-file: ['app/scripts/**/*']

# Any changes to file or subfolders in /openshift
'OpenShift':
  - changed-files:
    - any-glob-to-any-file: ['openshift/**/*']

# Any changes to file of subfolders in /tests
'Testing':
  - changed-files:
    - any-glob-to-any-file: ['tests/**/*']

# Any change to any file in any directory with a .env in name
'Environment Variables':
  - changed-files:
    - any-glob-to-any-file: ['**/*.env*']
