apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: NAME_SUFFIX
    displayName: Name Suffix
    description: A suffix appended to all objects
    required: true
  - name: ENV_NAME
    required: true
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: gwells}-${ENV_NAME}
      name: gwells-${ENV_NAME}-frontend
    spec:
      type: ClusterIP
      ports:
        - port: 80
          targetPort: 3005
          protocol: TCP
          name: 3005-tcp
      selector:
        service: gwells-${ENV_NAME}-frontend
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      labels:
        app: gwells-${ENV_NAME}
        deployment: gwells-${TENV_NAMEARGET}-frontend-${NAME_SUFFIX}
      name: gwells-${ENV_NAME}-frontend-${NAME_SUFFIX}
    spec:
      strategy:
        type: Recreate
      selector:
        matchLabels:
          deployment: gwells-${ENV_NAME}-frontend-${NAME_SUFFIX}
      template:
        metadata:
          labels:
            app: gwells-${ENV_NAME}
            deployment: gwells-${ENV_NAME}-frontend-${NAME_SUFFIX}
            service: gwells-${ENV_NAME}-frontend
        spec:
          containers:
            - name: gwells-${ENV_NAME}-frontend
              # image: ghcr.io/bcgov/gwells/frontend:${TAG}
              image: ghcr.io/bcgov/nr-gwells/frontend:69
              securityContext:
                capabilities:
                  add: ["NET_BIND_SERVICE"]
              imagePullPolicy: Always
              env:
                - name: LOG_LEVEL
                  value: info
                - name: VUE_APP_AXIOS_BASE_URL
                  value: http://gwells-${ENV_NAME}/gwells/api/v2/
                - name: BACKEND_URL
                  value: http://gwells-${ENV_NAME}
              ports:
                - name: container-port
                  containerPort: 3000
              # command: ["caddy", "run", "--config", "/etc/caddy/Caddyfile"]
              readinessProbe:
                httpGet:
                  port: container-port
                initialDelaySeconds: 90
                periodSeconds: 10
                timeoutSeconds: 10
                successThreshold: 3
                failureThreshold: 30
              livenessProbe:
                successThreshold: 1
                failureThreshold: 3
                httpGet:
                  port: container-port
                initialDelaySeconds: 15
                periodSeconds: 30
                timeoutSeconds: 5
              resources: # this is optional
                limits:
                  cpu: 150m
                  memory: 250Mi
                requests:
                  cpu: 50m
                  memory: 175Mi
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      labels:
        app: gwells-${ENV_NAME}
      name: gwells-${ENV_NAME}-frontend-${NAME_SUFFIX}
    spec:
      host: gwells-${ENV_NAME}.apps.silver.devops.gov.bc.ca
      port:
        targetPort: 3005-tcp
      to:
        kind: Service
        name: gwells-${ENV_NAME}-frontend
        weight: 100
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
