apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: NAME_SUFFIX
    displayName: Name Suffix
    description: A suffix appended to all objects
    required: true
  - name: IMAGE_TAG
    required: true
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: nr-gwells${NAME_SUFFIX}
      name: gwells${NAME_SUFFIX}-frontend
    spec:
      type: ClusterIP
      ports:
        - port: 3005
          targetPort: 3000
          protocol: TCP
          name: 3000-tcp
      selector:
        service: gwells${NAME_SUFFIX}-frontend
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      labels:
        app: nr-gwells-${NAME_SUFFIX}
        deployment: gwells-${NAME_SUFFIX}-frontend
      name: gwells-${NAME_SUFFIX}-frontend
    spec:
      strategy:
        type: Recreate
      selector:
        matchLabels:
          deployment: gwells-${NAME_SUFFIX}-frontend
      template:
        metadata:
          labels:
            app: nr-gwells-${NAME_SUFFIX}
            deployment: gwells-${NAME_SUFFIX}-frontend
            service: gwells-${NAME_SUFFIX}-frontend
        spec:
          containers:
            - name: gwells-${NAME_SUFFIX}-frontend
              image: ghcr.io/bcgov/nr-gwells/frontend:${IMAGE_TAG}
              securityContext:
                capabilities:
                  add: ["NET_BIND_SERVICE"]
              imagePullPolicy: Always
              env:
                - name: LOG_LEVEL
                  value: info
                - name: VUE_APP_AXIOS_BASE_URL
                  value: http://gwells-${NAME_SUFFIX}-frontend/gwells/api/v2/
                - name: BACKEND_URL
                  value: http://gwells-${NAME_SUFFIX}-frontend
              ports:
                - name: container-port
                  containerPort: 3000
                  protocol: TCP
              # command: ["caddy", "run", "--config", "/etc/caddy/Caddyfile"]
              # readinessProbe:
              #   httpGet:
              #     path: /health
              #     port: 3001
              #     scheme: HTTP
              #   initialDelaySeconds: 5
              #   periodSeconds: 2
              #   timeoutSeconds: 2
              #   successThreshold: 1
              #   failureThreshold: 30
              # livenessProbe:
              #   successThreshold: 1
              #   failureThreshold: 3
              #   httpGet:
              #     path: /health
              #     port: 3001
              #     scheme: HTTP
              #   initialDelaySeconds: 15
              #   periodSeconds: 30
              #   timeoutSeconds: 5
              resources: # this is optional
                limits:
                  cpu: 30m
                  memory: 40Mi
                requests:
                  cpu: 15m
                  memory: 20Mi
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      labels:
        app: nr-gwells-${NAME_SUFFIX}
      name: gwells-${NAME_SUFFIX}-frontend
    spec:
      host: gwells-${NAME_SUFFIX}-frontend.apps.silver.devops.gov.bc.ca
      port:
        targetPort: 3000-tcp
      to:
        kind: Service
        name: gwells-${NAME_SUFFIX}-frontend
        weight: 100
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
