apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: APP
    description: Application name
    value: gwells
  - name: COMPONENT
    description: Component name
    value: frontend
  - name: ORG
    description: Organization name; e.g. bcgov or bcdevops
    value: bcgov
  - name: TAG
    description: Image tag; e.g. PR number or latest
    required: true
  - name: TARGET
    description: Deployment target; e.g. PR number, test or prod
    required: true
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: ${APP}-${TARGET}
      name: ${APP}-${TARGET}-${COMPONENT}
    spec:
      type: ClusterIP
      ports:
        - port: 80
          targetPort: 3005
          protocol: TCP
          name: 3005-tcp
      selector:
        service: ${APP}-${TARGET}-${COMPONENT}
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      labels:
        app: ${APP}-${TARGET}
        deployment: ${APP}-${TARGET}-${COMPONENT}
      name: ${APP}-${TARGET}-${COMPONENT}
    spec:
      strategy:
        type: Recreate
      selector:
        matchLabels:
          deployment: ${APP}-${TARGET}-${COMPONENT}
      template:
        metadata:
          labels:
            app: ${APP}-${TARGET}
            deployment: ${APP}-${TARGET}-${COMPONENT}
            service: ${APP}-${TARGET}-${COMPONENT}
        spec:
          containers:
            - name: ${APP}-${TARGET}-${COMPONENT}
              # image: ghcr.io/${ORG}/${APP}/${COMPONENT}:${TAG}
              image: ghcr.io/bcgov/nr-gwells/frontend:69
              securityContext:
                capabilities:
                  add: ["NET_BIND_SERVICE"]
              imagePullPolicy: Always
              env:
                - name: LOG_LEVEL
                  value: info
                - name: VUE_APP_AXIOS_BASE_URL
                  value: http://${APP}-${TARGET}/gwells/api/v2/
                - name: BACKEND_URL
                  value: http://${APP}-${TARGET}
              ports:
                - name: container-port
                  containerPort: 3000
              # command: ["caddy", "run", "--config", "/etc/caddy/Caddyfile"]
              readinessProbe:
                httpGet:
                  port: container-port
                initialDelaySeconds: 90
                periodSeconds: 10
                timeoutSeconds: 10
                successThreshold: 3
                failureThreshold: 30
              livenessProbe:
                successThreshold: 1
                failureThreshold: 3
                httpGet:
                  port: container-port
                initialDelaySeconds: 15
                periodSeconds: 30
                timeoutSeconds: 5
              resources: # this is optional
                limits:
                  cpu: 150m
                  memory: 250Mi
                requests:
                  cpu: 50m
                  memory: 175Mi
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      labels:
        app: ${APP}-${TARGET}
      name: ${APP}-${TARGET}-${COMPONENT}
    spec:
      host: gwells-${TARGET}.apps.silver.devops.gov.bc.ca
      port:
        targetPort: 3005-tcp
      to:
        kind: Service
        name: ${APP}-${TARGET}-${COMPONENT}
        weight: 100
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
