kind: Template
apiVersion: template.openshift.io/v1
parameters:
- name: NAME_SUFFIX
  displayName: Name Suffix
  description: A suffix appended to all objects
  required: true
- name: ENV_NAME
  required: true
- name: HOST
  required: false
  value: ''
- name: CPU_REQUEST
  required: false
  value: 100m
- name: CPU_LIMIT
  required: false
  value: 500m
- name: MEMORY_REQUEST
  required: false
  value: 750Mi
- name: MEMORY_LIMIT
  required: false
  value: 1Gi
- name: PSQL_IMAGE
  description: A psql client image (a PostgreSQL image will suffice)
  required: true
  value: image-registry.openshift-image-registry.svc:5000/26e83e-tools/crunchy-postgres-gis:centos7-12.4-3.0-4.5.0
- name: DJANGO_ADMIN_PASSWORD
  required: true
- name: DJANGO_ADMIN_URL
  required: true
- name: DJANGO_ADMIN_USER
  required: true
- name: DJANGO_SECRET_KEY
  required: true
- name: E_LICENSING_AUTH_USERNAME
  required: true
- name: E_LICENSING_AUTH_PASSWORD
  required: true
- name: E_LICENSING_URL
  required: true
- name: DB_REPLICATE
  required: true
- name: DJANGO_DEBUG
  required: true
- name: ENABLE_ADDITIONAL_DOCUMENTS
  required: true
- name: S3_PRIVATE_BUCKET
  required: true
- name: S3_PRIVATE_HOST
  required: true
- name: S3_WELL_EXPORT_BUCKET
  required: true
- name: SSO_AUDIENCE
  required: true
- name: SSO_AUTH_HOST
  required: true
- name: SSO_CLIENT
  required: true
- name: SSO_IDP_HINT
  required: true
- name: SSO_PORT
  required: true
- name: SSO_PUBKEY
  required: true
- name: SSO_REALM
  required: true
- name: SSO_TEST_AUDIENCE
  required: true
- name: SSO_TEST_CLIENT
  required: true
- name: GDAL_LIBRARY_PATH
  required: true
- name: GEOS_LIBRARY_PATH
  required: true
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: nr-gwells${NAME_SUFFIX}
    creationTimestamp: 
    labels:
      base-name: gwells
      appver: nr-gwells${NAME_SUFFIX}
    annotations:
      description: Keeps track of changes in the application image
  spec:
    lookupPolicy:
      local: false
- kind: Secret
  apiVersion: v1
  type: Opaque
  metadata:
    name: minio-access-parameters${NAME_SUFFIX}
    creationTimestamp: 
    annotations:
      as-copy-of: nr-gwells-minio-secrets
  data:
    MINIO_ACCESS_KEY: 
    MINIO_SECRET_KEY: 
    S3_HOST: 
    S3_ROOT_BUCKET: 
    S3_PUBLIC_ACCESS_KEY: 
    S3_PUBLIC_SECRET_KEY: 
- kind: Secret
  apiVersion: v1
  metadata:
    creationTimestamp: 
    name: nr-gwells-django${NAME_SUFFIX}
  stringData:
    admin_password: ${DJANGO_ADMIN_PASSWORD}
    admin_url: ${DJANGO_ADMIN_URL}
    admin_user: ${DJANGO_ADMIN_USER}
    secret_key: ${DJANGO_SECRET_KEY}
- kind: Secret
  apiVersion: v1
  metadata:
    creationTimestamp: 
    name: nr-gwells-e-licensing${NAME_SUFFIX}
  stringData:
    E_LICENSING_AUTH_PASSWORD: ${E_LICENSING_AUTH_PASSWORD}
    E_LICENSING_AUTH_USERNAME: ${E_LICENSING_AUTH_USERNAME}
- kind: ConfigMap
  apiVersion: v1
  metadata:
    creationTimestamp: 
    name: nr-gwells-global-config${NAME_SUFFIX}
    labels:
      appver: nr-gwells${NAME_SUFFIX}
      app: nr-gwells${NAME_SUFFIX}
  stringData:
    DB_REPLICATE: ${DB_REPLICATE}
    DJANGO_DEBUG: ${DJANGO_DEBUG}
    ENABLE_ADDITIONAL_DOCUMENTS: ${ENABLE_ADDITIONAL_DOCUMENTS}
    E_LICENSING_URL: ${E_LICENSING_URL}
    S3_PRIVATE_BUCKET: ${S3_PRIVATE_BUCKET}
    S3_PRIVATE_HOST: ${S3_PRIVATE_HOST}
    S3_WELL_EXPORT_BUCKET: ${S3_WELL_EXPORT_BUCKET} 
    SSO_AUDIENCE: ${SSO_AUDIENCE}
    SSO_AUTH_HOST: ${SSO_AUTH_HOST}
    SSO_CLIENT: ${SSO_CLIENT}
    SSO_IDP_HINT: ${SSO_IDP_HINT}
    SSO_PORT: ${SSO_PORT}
    SSO_PUBKEY: ${SSO_PUBKEY}
    SSO_REALM: ${SSO_REALM}
    SSO_TEST_AUDIENCE: ${SSO_TEST_AUDIENCE}
    SSO_TEST_CLIENT: ${SSO_TEST_CLIENT}
    GDAL_LIBRARY_PATH: ${GDAL_LIBRARY_PATH}
    GEOS_LIBRARY_PATH: ${GEOS_LIBRARY_PATH}

- kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: nr-gwells${NAME_SUFFIX}
    creationTimestamp: 
    labels:
      appver: nr-gwells${NAME_SUFFIX}
    annotations:
      description: Defines how to deploy the application server
  spec:
    strategy:
      type: RollingUpdate
      rollingParams:
        timeoutSeconds: 900
        # pre:
        #   failurePolicy: Abort
        #   execNewPod:
        #     command:
        #     - "/usr/bin/container-entrypoint"
        #     - "/opt/app-root/src/scripts/pre-deploy.sh"
        #     containerName: nr-gwells-app${NAME_SUFFIX}
        #     env:
        #     - name: PGDATABASE
        #       valueFrom:
        #         secretKeyRef:
        #           name: nr-gwells-pg12${NAME_SUFFIX}
        #           key: database-name
        #     - name: PGUSER
        #       valueFrom:
        #         secretKeyRef:
        #           name: nr-gwells-pg12${NAME_SUFFIX}
        #           key: database-user
        #     - name: PGPASSWORD
        #       valueFrom:
        #         secretKeyRef:
        #           name: nr-gwells-pg12${NAME_SUFFIX}
        #           key: database-password
        #     - name: PGHOST
        #       value: nr-gwells-pg12${NAME_SUFFIX}
      resources: {}
      activeDeadlineSeconds: 21600
    replicas: 2
    test: false
    selector:
      name: nr-gwells${NAME_SUFFIX}
      matchLabels:
        deployment: nr-gwells${NAME_SUFFIX}
    template:
      metadata:
        name: nr-gwells${NAME_SUFFIX}
        creationTimestamp: 
        labels:
          name: nr-gwells${NAME_SUFFIX}
          appver: nr-gwells${NAME_SUFFIX}
          deployment: nr-gwells${NAME_SUFFIX}
      spec:
        # initContainers:
        # - name: check-db
        #   image: "${PSQL_IMAGE}"
        #   command:
        #   - "/bin/bash"
        #   - "-c"
        #   - psql -qtAX -c 'select 1'
        #   env:
        #   - name: PGDATABASE
        #     valueFrom:
        #       secretKeyRef:
        #         name: nr-gwells-pg12${NAME_SUFFIX}
        #         key: database-name
        #   - name: PGUSER
        #     valueFrom:
        #       secretKeyRef:
        #         name: nr-gwells-pg12${NAME_SUFFIX}
        #         key: database-user
        #   - name: PGPASSWORD
        #     valueFrom:
        #       secretKeyRef:
        #         name: nr-gwells-pg12${NAME_SUFFIX}
        #         key: database-password
        #   - name: PGHOST
        #     value: nr-gwells-pg12${NAME_SUFFIX}
        #   resources:
        #     limits:
        #       cpu: 50m
        #       memory: 256Mi
        #     requests:
        #       cpu: 10m
        #       memory: 128Mi
        containers:
        - name: nr-gwells-app${NAME_SUFFIX}
          image: 'ghcr.io/bcgov/nr-gwells/backend:54'
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
          - name: DATABASE_SERVICE_NAME
            value: nr-gwells-pg12${NAME_SUFFIX}
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: nr-gwells-pg12${NAME_SUFFIX}
                key: database-name
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: nr-gwells-pg12${NAME_SUFFIX}
                key: database-user
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nr-gwells-pg12${NAME_SUFFIX}
                key: database-password
          - name: DATABASE_SCHEMA
            value: public
          - name: APP_MODULE
            value: wsgi:application
          - name: APP_HOME
            value: backend
          - name: APP_CONFIG
            value: "/opt/app-root/src/backend/gunicorn.ocp4.cfg"
          - name: DJANGO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: nr-gwells-django${NAME_SUFFIX}
                key: secret_key
          - name: DJANGO_ADMIN_URL
            valueFrom:
              secretKeyRef:
                name: nr-gwells-django${NAME_SUFFIX}
                key: admin_url
          - name: DJANGO_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: nr-gwells-django${NAME_SUFFIX}
                key: admin_user
          - name: DJANGO_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nr-gwells-django${NAME_SUFFIX}
                key: admin_password
          - name: E_LICENSING_AUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nr-gwells-e-licensing${NAME_SUFFIX}
                key: E_LICENSING_AUTH_PASSWORD
          - name: E_LICENSING_AUTH_USERNAME
            valueFrom:
              secretKeyRef:
                name: nr-gwells-e-licensing${NAME_SUFFIX}
                key: E_LICENSING_AUTH_USERNAME
          - name: E_LICENSING_URL
            valueFrom:
              configMapKeyRef:
                name: nr-gwells-global-config${NAME_SUFFIX}
                key: E_LICENSING_URL
          - name: DJANGO_DEBUG
            valueFrom:
              configMapKeyRef:
                key: DJANGO_DEBUG
                name: nr-gwells-global-config${NAME_SUFFIX}
          - name: GDAL_LIBRARY_PATH
            valueFrom:
              configMapKeyRef:
                key: GDAL_LIBRARY_PATH
                name: nr-gwells-global-config${NAME_SUFFIX}
          - name: GEOS_LIBRARY_PATH
            valueFrom:
              configMapKeyRef:
                key: GEOS_LIBRARY_PATH
                name: nr-gwells-global-config${NAME_SUFFIX}
          - name: S3_AQUIFER_BUCKET
            valueFrom:
              configMapKeyRef:
                key: S3_AQUIFER_BUCKET
                name: nr-gwells-global-config${NAME_SUFFIX}
          - name: S3_REGISTRANT_BUCKET
            valueFrom:
              configMapKeyRef:
                key: S3_REGISTRANT_BUCKET
                name: nr-gwells-global-config${NAME_SUFFIX}
          - name: S3_PRIVATE_ROOT_BUCKET
            valueFrom:
              configMapKeyRef:
                key: S3_PRIVATE_ROOT_BUCKET
                name: nr-gwells-global-config${NAME_SUFFIX}
          - name: S3_PRIVATE_AQUIFER_BUCKET
            valueFrom:
              configMapKeyRef:
                key: S3_PRIVATE_AQUIFER_BUCKET
                name: nr-gwells-global-config${NAME_SUFFIX}
          - name: S3_PRIVATE_REGISTRANT_BUCKET
            valueFrom:
              configMapKeyRef:
                key: S3_PRIVATE_REGISTRANT_BUCKET
                name: nr-gwells-global-config${NAME_SUFFIX}
          - name: S3_PRIVATE_WELL_BUCKET
            valueFrom:
              configMapKeyRef:
                key: S3_PRIVATE_WELL_BUCKET
                name: nr-gwells-global-config${NAME_SUFFIX}
          - name: SSO_CLIENT
            valueFrom:
              configMapKeyRef:
                key: SSO_CLIENT
                name: nr-gwells-global-config${NAME_SUFFIX}
          - name: SSO_PUBKEY
            valueFrom:
              configMapKeyRef:
                key: SSO_PUBKEY
                name: nr-gwells-global-config${NAME_SUFFIX}
          - name: SSO_AUTH_HOST
            valueFrom:
              configMapKeyRef:
                key: SSO_AUTH_HOST
                name: nr-gwells-global-config${NAME_SUFFIX}
          - name: SSO_AUDIENCE
            valueFrom:
              configMapKeyRef:
                key: SSO_AUDIENCE
                name: nr-gwells-global-config${NAME_SUFFIX}
          - name: SSO_REALM
            valueFrom:
              configMapKeyRef:
                key: SSO_REALM
                name: nr-gwells-global-config${NAME_SUFFIX}
          - name: SSO_PORT
            valueFrom:
              configMapKeyRef:
                key: SSO_PORT
                name: nr-gwells-global-config${NAME_SUFFIX}
          - name: SSO_TEST_CLIENT
            valueFrom:
              configMapKeyRef:
                key: SSO_TEST_CLIENT
                name: nr-gwells-global-config${NAME_SUFFIX}
          - name: SSO_TEST_AUDIENCE
            valueFrom:
              configMapKeyRef:
                key: SSO_TEST_AUDIENCE
                name: nr-gwells-global-config${NAME_SUFFIX}
          - name: ENABLE_ADDITIONAL_DOCUMENTS
            valueFrom:
              configMapKeyRef:
                key: ENABLE_ADDITIONAL_DOCUMENTS
                name: nr-gwells-global-config${NAME_SUFFIX}
          - name: ENABLE_AQUIFERS_SEARCH
            valueFrom:
              configMapKeyRef:
                key: ENABLE_AQUIFERS_SEARCH
                name: nr-gwells-global-config${NAME_SUFFIX}
          - name: APP_CONTEXT_ROOT
            value: gwells
          - name: SESSION_COOKIE_SECURE
            value: 'True'
          - name: CSRF_COOKIE_SECURE
            value: 'True'
          - name: DB_REPLICATE
            valueFrom:
              configMapKeyRef:
                key: DB_REPLICATE
                name: nr-gwells-global-config${NAME_SUFFIX}
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-access-parameters${NAME_SUFFIX}
                key: MINIO_ACCESS_KEY
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: minio-access-parameters${NAME_SUFFIX}
                key: MINIO_SECRET_KEY
          - name: S3_PUBLIC_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-access-parameters${NAME_SUFFIX}
                key: S3_PUBLIC_ACCESS_KEY
          - name: S3_PUBLIC_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: minio-access-parameters${NAME_SUFFIX}
                key: S3_PUBLIC_SECRET_KEY
          - name: S3_HOST
            valueFrom:
              secretKeyRef:
                name: minio-access-parameters${NAME_SUFFIX}
                key: S3_HOST
          - name: S3_ROOT_BUCKET
            valueFrom:
              secretKeyRef:
                name: minio-access-parameters${NAME_SUFFIX}
                key: S3_ROOT_BUCKET
          - name: S3_PRIVATE_HOST
            valueFrom:
              configMapKeyRef:
                key: S3_PRIVATE_HOST
                name: nr-gwells-global-config${NAME_SUFFIX}
          - name: S3_WELL_EXPORT_BUCKET
            valueFrom:
              configMapKeyRef:
                key: S3_WELL_EXPORT_BUCKET
                name: nr-gwells-global-config${NAME_SUFFIX}
          - name: S3_PRIVATE_BUCKET
            valueFrom:
              configMapKeyRef:
                key: S3_PRIVATE_BUCKET
                name: nr-gwells-global-config${NAME_SUFFIX}
          - name: SSO_IDP_HINT
            valueFrom:
              configMapKeyRef:
                key: SSO_IDP_HINT
                name: nr-gwells-global-config${NAME_SUFFIX}
          - name: WEB_CONCURRENCY
            value: '4'
          - name: GUNICORN_WORKERS
            value: '4'
          - name: ENFORCE_ENV_VARIABLES
            value: 'False'
          - name: EMAIL_NOTIFICATION_RECIPIENT
            valueFrom:
              configMapKeyRef:
                key: EMAIL_NOTIFICATION_RECIPIENT
                name: nr-gwells-global-config${NAME_SUFFIX}
          - name: GEOCODER_ADDRESS_API_BASE
            valueFrom:
              configMapKeyRef:
                key: GEOCODER_ADDRESS_API_BASE
                name: nr-gwells-global-config${NAME_SUFFIX}
          resources:
            limits:
              cpu: "${CPU_LIMIT}"
              memory: "${MEMORY_LIMIT}"
            requests:
              cpu: "${CPU_REQUEST}"
              memory: "${MEMORY_REQUEST}"
          livenessProbe:
            httpGet:
              path: "/gwells/health"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: "/gwells/health"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 10
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    creationTimestamp: 
    labels:
      appver: nr-gwells${NAME_SUFFIX}
    name: nr-gwells${NAME_SUFFIX}
  spec:
    maxReplicas: 5
    minReplicas: 2
    scaleTargetRef:
      apiVersion: v1
      kind: Deployment
      name: nr-gwells${NAME_SUFFIX}
    targetCPUUtilizationPercentage: 90
- kind: Service
  apiVersion: v1
  metadata:
    name: nr-gwells${NAME_SUFFIX}
    creationTimestamp: 
    labels:
      appver: nr-gwells${NAME_SUFFIX}
    annotations:
      description: Exposes and load balances the application pods
  spec:
    ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      name: nr-gwells${NAME_SUFFIX}
    type: ClusterIP
    sessionAffinity: None
- kind: Route
  apiVersion: v1
  metadata:
    name: nr-gwells${NAME_SUFFIX}
    creationTimestamp: 
    labels:
      frontend: 'true'
      appver: nr-gwells${NAME_SUFFIX}
    annotations: {}
  spec:
    host: "${HOST}"
    path: "/gwells"
    to:
      kind: Service
      name: nr-gwells${NAME_SUFFIX}
      weight: 100
    port:
      targetPort: web
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    wildcardPolicy: None
