kind: Template
apiVersion: template.openshift.io/v1
parameters:
  - name: REPO
    description: Repository name
    value: nr-gwells
  - name: COMPONENT
    description: Component name
    value: backend
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: TAG
    required: true
  - name: CPU_REQUEST
    required: false
    value: 25m
  - name: CPU_LIMIT
    required: false
    value: 100m
  - name: MEMORY_REQUEST
    required: false
    value: 150Mi
  - name: MEMORY_LIMIT
    required: false
    value: 450Mi
  - name: E_LICENSING_URL
    required: true
  - name: DB_REPLICATE
    required: true
  - name: DJANGO_DEBUG
    required: true
  - name: ENABLE_ADDITIONAL_DOCUMENTS
    required: true
  - name: S3_PRIVATE_BUCKET
    required: true
  - name: S3_PRIVATE_HOST
    required: true
  - name: S3_WELL_EXPORT_BUCKET
    required: true
  - name: SSO_AUDIENCE
    required: true
  - name: SSO_AUTH_HOST
    required: true
  - name: SSO_CLIENT
    required: true
  - name: SSO_IDP_HINT
    required: true
  - name: SSO_PORT
    required: true
  - name: SSO_PUBKEY
    required: true
  - name: SSO_REALM
    required: true
  - name: SSO_TEST_AUDIENCE
    required: true
  - name: SSO_TEST_CLIENT
    required: true
  - name: GDAL_LIBRARY_PATH
    required: true
  - name: GEOS_LIBRARY_PATH
    required: true
  - name: S3_AQUIFER_BUCKET
    required: true
  - name: S3_REGISTRANT_BUCKET
    required: true
  - name: S3_PRIVATE_ROOT_BUCKET
    required: true
  - name: S3_PRIVATE_AQUIFER_BUCKET
    required: true
  - name: S3_PRIVATE_REGISTRANT_BUCKET
    required: true
  - name: S3_PRIVATE_WELL_BUCKET
    required: true
  - name: ENABLE_AQUIFERS_SEARCH
    required: true
  - name: EMAIL_NOTIFICATION_RECIPIENT
    required: true
  - name: GEOCODER_ADDRESS_API_BASE
    required: true
objects:
- kind: ConfigMap
  apiVersion: v1
  metadata:
    creationTimestamp: 
    name: ${REPO}-${ZONE}-global-config
    labels:
      appver: ${REPO}-${ZONE}
      app: ${REPO}-${ZONE}
  data:
    DB_REPLICATE: ${DB_REPLICATE}
    DJANGO_DEBUG: ${DJANGO_DEBUG}
    ENABLE_ADDITIONAL_DOCUMENTS: ${ENABLE_ADDITIONAL_DOCUMENTS}
    E_LICENSING_URL: ${E_LICENSING_URL}
    S3_PRIVATE_BUCKET: ${S3_PRIVATE_BUCKET}
    S3_PRIVATE_HOST: ${S3_PRIVATE_HOST}
    S3_WELL_EXPORT_BUCKET: ${S3_WELL_EXPORT_BUCKET}
    S3_AQUIFER_BUCKET: ${S3_AQUIFER_BUCKET}
    SSO_AUDIENCE: ${SSO_AUDIENCE}
    SSO_AUTH_HOST: ${SSO_AUTH_HOST}
    SSO_CLIENT: ${SSO_CLIENT}
    SSO_IDP_HINT: ${SSO_IDP_HINT}
    SSO_PORT: ${SSO_PORT}
    SSO_PUBKEY: ${SSO_PUBKEY}
    SSO_REALM: ${SSO_REALM}
    SSO_TEST_AUDIENCE: ${SSO_TEST_AUDIENCE}
    SSO_TEST_CLIENT: ${SSO_TEST_CLIENT}
    # GDAL_LIBRARY_PATH: ${GDAL_LIBRARY_PATH}
    # GEOS_LIBRARY_PATH: ${GEOS_LIBRARY_PATH}
    # S3_REGISTRANT_BUCKET: ${S3_REGISTRANT_BUCKET}
    # S3_PRIVATE_ROOT_BUCKET: ${S3_PRIVATE_ROOT_BUCKET}
    # S3_PRIVATE_AQUIFER_BUCKET: ${S3_PRIVATE_AQUIFER_BUCKET}
    # S3_PRIVATE_REGISTRANT_BUCKET: ${S3_PRIVATE_REGISTRANT_BUCKET}
    # S3_PRIVATE_WELL_BUCKET: ${S3_PRIVATE_WELL_BUCKET}
    # ENABLE_AQUIFERS_SEARCH: ${ENABLE_AQUIFERS_SEARCH}
    # EMAIL_NOTIFICATION_RECIPIENT: ${EMAIL_NOTIFICATION_RECIPIENT}
    # GEOCODER_ADDRESS_API_BASE: ${GEOCODER_ADDRESS_API_BASE}
- kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: ${REPO}-${ZONE}-${COMPONENT}
    creationTimestamp: 
    labels:
      app: ${REPO}-${ZONE}-${COMPONENT}
    annotations:
      description: Defines how to deploy the application server
  spec:
    strategy:
      type: RollingUpdate
      rollingParams:
        timeoutSeconds: 900
        # pre:
        #   failurePolicy: Abort
        #   execNewPod:
        #     command:
        #     - "/usr/bin/container-entrypoint"
        #     - "/opt/app-root/src/scripts/pre-deploy.sh"
        #     containerName: ${REPO}-${ZONE}-${COMPONENT}-app
        #     env:
        #     - name: PGDATABASE
        #       valueFrom:
        #         secretKeyRef:
        #           name: ${REPO}-${ZONE}-${COMPONENT}-pg12
        #           key: database-name
        #     - name: PGUSER
        #       valueFrom:
        #         secretKeyRef:
        #           name: ${REPO}-${ZONE}-${COMPONENT}-pg12
        #           key: database-user
        #     - name: PGPASSWORD
        #       valueFrom:
        #         secretKeyRef:
        #           name: ${REPO}-${ZONE}-${COMPONENT}-pg12
        #           key: database-password
        #     - name: PGHOST
        #       value: ${REPO}-${ZONE}-${COMPONENT}-pg12
      resources: {}
      activeDeadlineSeconds: 21600
    replicas: 1
    test: false
    selector:
      name: ${REPO}-${ZONE}-${COMPONENT}
      matchLabels:
        deployment: ${REPO}-${ZONE}-${COMPONENT}
    template:
      metadata:
        name: ${REPO}-${ZONE}-${COMPONENT}
        creationTimestamp: 
        labels:
          name: ${REPO}-${ZONE}-${COMPONENT}
          deployment: ${REPO}-${ZONE}-${COMPONENT}
      spec:
        volumes:
          - name: staticfiles
            emptyDir:
              sizeLimit: 250Mi
        containers:
        - name: ${REPO}-${ZONE}-${COMPONENT}-app
          image: 'ghcr.io/bcgov/${REPO}/${COMPONENT}:${TAG}'
          volumeMounts:
            - name: staticfiles
              mountPath: /app/staticfiles
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
          - name: DATABASE_SERVICE_NAME
            value: ${REPO}-database-${ZONE}
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: ${REPO}-database-${ZONE}
                key: database-name
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: ${REPO}-database-${ZONE}
                key: database-user
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${REPO}-database-${ZONE}
                key: database-password
          - name: DATABASE_SCHEMA
            value: public
          - name: APP_MODULE
            value: wsgi:application
          - name: APP_HOME
            value: ${COMPONENT}
          - name: APP_CONFIG
            value: "/opt/app-root/src/${COMPONENT}/gunicorn.ocp4.cfg"
          - name: DJANGO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: ${REPO}-django-${ZONE}
                key: secret_key
          - name: DJANGO_ADMIN_URL
            valueFrom:
              secretKeyRef:
                name: ${REPO}-django-${ZONE}
                key: admin_url
          - name: DJANGO_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: ${REPO}-django-${ZONE}
                key: admin_user
          - name: DJANGO_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${REPO}-django-${ZONE}
                key: admin_password
          - name: E_LICENSING_AUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${REPO}-e-licensing-${ZONE}
                key: E_LICENSING_AUTH_PASSWORD
          - name: E_LICENSING_AUTH_USERNAME
            valueFrom:
              secretKeyRef:
                name: ${REPO}-e-licensing-${ZONE}
                key: E_LICENSING_AUTH_USERNAME
          - name: E_LICENSING_URL
            valueFrom:
              configMapKeyRef:
                name: ${REPO}-${ZONE}-global-config
                key: E_LICENSING_URL
          - name: DJANGO_DEBUG
            valueFrom:
              configMapKeyRef:
                key: DJANGO_DEBUG
                name: ${REPO}-${ZONE}-global-config
          - name: GDAL_LIBRARY_PATH
            valueFrom:
              configMapKeyRef:
                key: GDAL_LIBRARY_PATH
                name: ${REPO}-${ZONE}-global-config
          - name: GEOS_LIBRARY_PATH
            valueFrom:
              configMapKeyRef:
                key: GEOS_LIBRARY_PATH
                name: ${REPO}-${ZONE}-global-config
          - name: S3_AQUIFER_BUCKET
            valueFrom:
              configMapKeyRef:
                key: S3_AQUIFER_BUCKET
                name: ${REPO}-${ZONE}-global-config
          - name: S3_REGISTRANT_BUCKET
            valueFrom:
              configMapKeyRef:
                key: S3_REGISTRANT_BUCKET
                name: ${REPO}-${ZONE}-global-config
          - name: S3_PRIVATE_ROOT_BUCKET
            valueFrom:
              configMapKeyRef:
                key: S3_PRIVATE_ROOT_BUCKET
                name: ${REPO}-${ZONE}-global-config
          - name: S3_PRIVATE_AQUIFER_BUCKET
            valueFrom:
              configMapKeyRef:
                key: S3_PRIVATE_AQUIFER_BUCKET
                name: ${REPO}-${ZONE}-global-config
          - name: S3_PRIVATE_REGISTRANT_BUCKET
            valueFrom:
              configMapKeyRef:
                key: S3_PRIVATE_REGISTRANT_BUCKET
                name: ${REPO}-${ZONE}-global-config
          - name: S3_PRIVATE_WELL_BUCKET
            valueFrom:
              configMapKeyRef:
                key: S3_PRIVATE_WELL_BUCKET
                name: ${REPO}-${ZONE}-global-config
          - name: SSO_CLIENT
            valueFrom:
              configMapKeyRef:
                key: SSO_CLIENT
                name: ${REPO}-${ZONE}-global-config
          - name: SSO_PUBKEY
            valueFrom:
              configMapKeyRef:
                key: SSO_PUBKEY
                name: ${REPO}-${ZONE}-global-config
          - name: SSO_AUTH_HOST
            valueFrom:
              configMapKeyRef:
                key: SSO_AUTH_HOST
                name: ${REPO}-${ZONE}-global-config
          - name: SSO_AUDIENCE
            valueFrom:
              configMapKeyRef:
                key: SSO_AUDIENCE
                name: ${REPO}-${ZONE}-global-config
          - name: SSO_REALM
            valueFrom:
              configMapKeyRef:
                key: SSO_REALM
                name: ${REPO}-${ZONE}-global-config
          - name: SSO_PORT
            valueFrom:
              configMapKeyRef:
                key: SSO_PORT
                name: ${REPO}-${ZONE}-global-config
          - name: SSO_TEST_CLIENT
            valueFrom:
              configMapKeyRef:
                key: SSO_TEST_CLIENT
                name: ${REPO}-${ZONE}-global-config
          - name: SSO_TEST_AUDIENCE
            valueFrom:
              configMapKeyRef:
                key: SSO_TEST_AUDIENCE
                name: ${REPO}-${ZONE}-global-config
          - name: ENABLE_ADDITIONAL_DOCUMENTS
            valueFrom:
              configMapKeyRef:
                key: ENABLE_ADDITIONAL_DOCUMENTS
                name: ${REPO}-${ZONE}-global-config
          - name: ENABLE_AQUIFERS_SEARCH
            valueFrom:
              configMapKeyRef:
                key: ENABLE_AQUIFERS_SEARCH
                name: ${REPO}-${ZONE}-global-config
          - name: APP_CONTEXT_ROOT
            value: ${REPO}
          - name: SESSION_COOKIE_SECURE
            value: 'true'
          - name: CSRF_COOKIE_SECURE
            value: 'true'
          - name: DB_REPLICATE
            valueFrom:
              configMapKeyRef:
                key: DB_REPLICATE
                name: ${REPO}-${ZONE}-global-config
          # - name: MINIO_ACCESS_KEY
          #   valueFrom:
          #     secretKeyRef:
          #       name: minio-access-parameters-${ZONE}
          #       key: MINIO_ACCESS_KEY
          # - name: MINIO_SECRET_KEY
          #   valueFrom:
          #     secretKeyRef:
          #       name: minio-access-parameters-${ZONE}
          #       key: MINIO_SECRET_KEY
          # - name: S3_PUBLIC_ACCESS_KEY
          #   valueFrom:
          #     secretKeyRef:
          #       name: minio-access-parameters-${ZONE}
          #       key: S3_PUBLIC_ACCESS_KEY
          # - name: S3_PUBLIC_SECRET_KEY
          #   valueFrom:
          #     secretKeyRef:
          #       name: minio-access-parameters-${ZONE}
          #       key: S3_PUBLIC_SECRET_KEY
          # - name: S3_HOST
          #   valueFrom:
          #     secretKeyRef:
          #       name: minio-access-parameters-${ZONE}
          #       key: S3_HOST
          # - name: S3_ROOT_BUCKET
          #   valueFrom:
          #     secretKeyRef:
          #       name: minio-access-parameters-${ZONE}
          #       key: S3_ROOT_BUCKET
          - name: S3_PRIVATE_HOST
            valueFrom:
              configMapKeyRef:
                key: S3_PRIVATE_HOST
                name: ${REPO}-${ZONE}-global-config
          - name: S3_WELL_EXPORT_BUCKET
            valueFrom:
              configMapKeyRef:
                key: S3_WELL_EXPORT_BUCKET
                name: ${REPO}-${ZONE}-global-config
          - name: S3_PRIVATE_BUCKET
            valueFrom:
              configMapKeyRef:
                key: S3_PRIVATE_BUCKET
                name: ${REPO}-${ZONE}-global-config
          - name: SSO_IDP_HINT
            valueFrom:
              configMapKeyRef:
                key: SSO_IDP_HINT
                name: ${REPO}-${ZONE}-global-config
          - name: WEB_CONCURRENCY
            value: '4'
          - name: GUNICORN_WORKERS
            value: '4'
          - name: ENFORCE_ENV_VARIABLES
            value: 'false'
          - name: EMAIL_NOTIFICATION_RECIPIENT
            valueFrom:
              configMapKeyRef:
                key: EMAIL_NOTIFICATION_RECIPIENT
                name: ${REPO}-${ZONE}-global-config
          - name: GEOCODER_ADDRESS_API_BASE
            valueFrom:
              configMapKeyRef:
                key: GEOCODER_ADDRESS_API_BASE
                name: ${REPO}-${ZONE}-global-config
          resources:
            limits:
              cpu: "${CPU_LIMIT}"
              memory: "${MEMORY_LIMIT}"
            requests:
              cpu: "${CPU_REQUEST}"
              memory: "${MEMORY_REQUEST}"
          # readinessProbe:
          #   httpGet:
          #     path: /gwells/health
          #     port: 8080
          #     scheme: HTTP
          #   initialDelaySeconds: 20
          #   timeoutSeconds: 3
          #   periodSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 5
          # livenessProbe:
          #   httpGet:
          #     path: /gwells/health
          #     port: 8080
          #     scheme: HTTP
          #   initialDelaySeconds: 20
          #   timeoutSeconds: 3
          #   periodSeconds: 30
          #   successThreshold: 1
          #   failureThreshold: 5
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    creationTimestamp: 
    labels:
      app: ${REPO}-${ZONE}
      appver: ${REPO}-${ZONE}-${COMPONENT}
    name: ${REPO}-${ZONE}-${COMPONENT}
  spec:
    maxReplicas: 5
    minReplicas: 1
    scaleTargetRef:
      apiVersion: v1
      kind: Deployment
      name: ${REPO}-${ZONE}-${COMPONENT}
    targetCPUUtilizationPercentage: 90
- kind: Service
  apiVersion: v1
  metadata:
    name: ${REPO}-${ZONE}-${COMPONENT}
    creationTimestamp: 
    labels:
      app: ${REPO}-${ZONE}-${COMPONENT}
  spec:
    ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      name: ${REPO}-${ZONE}-${COMPONENT}
    type: ClusterIP
    sessionAffinity: None
- kind: Route
  apiVersion: v1
  metadata:
    name: ${REPO}-${ZONE}-${COMPONENT}
    labels:
      frontend: 'true'
      app: ${REPO}-${ZONE}-${COMPONENT}
  spec:
    host: ${REPO}-${ZONE}-${COMPONENT}.apps.silver.devops.gov.bc.ca
    path: "/gwells"
    to:
      kind: Service
      name: ${REPO}-${ZONE}-${COMPONENT}
      weight: 100
    port:
      targetPort: web
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    wildcardPolicy: None
