apiVersion: v1
kind: Template
labels:
  template: pgtileserv-template
metadata:
  creationTimestamp: null
  name: pgtileserv-dc
parameters:
  - name: IMAGE_TAG
    value: '20200610'
  - name: NAME_SUFFIX
    required: true
  - name: DATABASE_SERVICE_NAME
    required: true
  - description: Request for CPU resources measured in cpu units, e.g. 200m
    displayName: CPU resource request
    name: REQUEST_CPU
    required: false
    value: 100m
  - description: Request for memory resources measured in bytes, e.g. 512Mi, 1Gi.
    displayName: Memory resource request
    name: REQUEST_MEMORY
    required: false
    value: 256Mi
  - description: Limit for CPU resources measured in cpu units, e.g. 200m
    displayName: CPU resource limit
    name: LIMIT_CPU
    required: false
    value: 200m
  - description: Limit for memory resources measured in bytes, e.g. 512Mi, 1Gi.
    displayName: Memory resource limit
    name: LIMIT_MEMORY
    required: false
    value: 512Mi
  - name: HOST
    required: true
objects:

  - apiVersion: v1
    kind: Route
    metadata:
      name: pgtileserv${NAME_SUFFIX}
      labels:
        app: gwells${NAME_SUFFIX}
        name: pgtileserv${NAME_SUFFIX}
        appver: gwells${NAME_SUFFIX}
        component: pgtileserv
    spec:
      host: ${HOST}
      path: /gwells/tiles
      to:
        kind: Service
        name: pgtileserv${NAME_SUFFIX}
        weight: 100
      port:
        targetPort: 8080
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      wildcardPolicy: None
  - apiVersion: v1
    kind: Service
    metadata:
      name: pgtileserv${NAME_SUFFIX}
    spec:
      ports:
        - port: 8080
          protocol: TCP
      selector:
        name: pgtileserv${NAME_SUFFIX}
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: pgtileserv${NAME_SUFFIX}
    spec:
      replicas: 1
      selector:
        name: pgtileserv${NAME_SUFFIX}
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: gwells${NAME_SUFFIX}
            name: pgtileserv${NAME_SUFFIX}
            appver: gwells${NAME_SUFFIX}
        spec:
          volumes:
          containers:
            - name: nginx
              image: docker-registry.default.svc:5000/moe-gwells-tools/nginx-tilecache
              imagePullPolicy: IfNotPresent
              readinessProbe:
                failureThreshold: 3
                initialDelaySeconds: 10
                periodSeconds: 10
                successThreshold: 1
                httpGet:
                  path: /health
                  port: 8080
                timeoutSeconds: 1
              livenessProbe:
                failureThreshold: 3
                initialDelaySeconds: 10
                periodSeconds: 10
                successThreshold: 1
                httpGet:
                  path: /health
                  port: 8080
                timeoutSeconds: 1
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 200m
                  memory: 256Mi
            - capabilities: {}
              env:
                - name: DATABASE_HOST
                  value: ${DATABASE_SERVICE_NAME}
                - name: PG_DATABASE
                  valueFrom:
                    secretKeyRef:
                        key: database-name
                        name: ${DATABASE_SERVICE_NAME}
                - name: PG_PASSWORD
                  valueFrom:
                    secretKeyRef:
                        key: database-password
                        name: ${DATABASE_SERVICE_NAME}
                - name: PG_USER
                  value: ftw_reader
                - name: DATABASE_URL
                  value: postgres://$(PG_USER):$(PG_PASSWORD)@$(DATABASE_HOST)/gwells
              image: docker-registry.default.svc:5000/moe-gwells-tools/pg_tileserv:${IMAGE_TAG}
              imagePullPolicy: IfNotPresent
              livenessProbe:
                failureThreshold: 3
                initialDelaySeconds: 5
                periodSeconds: 30
                successThreshold: 1
                tcpSocket:
                  port: 7800
                timeoutSeconds: 5
              name: pgtileserv
              ports:
                - containerPort: 7800
                  protocol: TCP
              readinessProbe:
                httpGet:
                  path: /
                  port: 7800
                failureThreshold: 3
                initialDelaySeconds: 10
                periodSeconds: 30
                successThreshold: 1
                timeoutSeconds: 5
              resources:
                requests:
                  cpu: ${REQUEST_CPU}
                  memory: ${REQUEST_MEMORY}
                limits:
                  cpu: ${LIMIT_CPU}
                  memory: ${LIMIT_MEMORY}
              securityContext:
                capabilities: {}
                privileged: false
              terminationMessagePath: /dev/termination-log
          dnsPolicy: ClusterFirst
          restartPolicy: Always
      triggers:
        - type: ConfigChange
    status: {}
