kind: Template
apiVersion: template.openshift.io/v1
parameters:
  - name: REPO
    description: Repository name
    value: nr-gwells
  - name: COMPONENT
    description: Component name
    value: database
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: TAG
    required: true
  - description: Volume space available for data, e.g. 512Mi, 2Gi.
    displayName: Volume Capacity
    name: VOLUME_CAPACITY
    value: 250Mi
  - description: Request for CPU resources measured in cpu units, e.g. 200m
    displayName: CPU resource request
    name: REQUEST_CPU
    required: false
    value: 20m
  - description: Request for memory resources measured in bytes, e.g. 512Mi, 1Gi.
    displayName: Memory resource request
    name: REQUEST_MEMORY
    required: false
    value: 150Mi
  - description: Limit for CPU resources measured in cpu units, e.g. 200m
    displayName: CPU resource limit
    name: LIMIT_CPU
    required: false
    value: 100m
  - description: Limit for memory resources measured in bytes, e.g. 512Mi, 1Gi.
    displayName: Memory resource limit
    name: LIMIT_MEMORY
    required: false
    value: 450Mi
  - description: Version of PostgreSQL image to be used (9.5 or 9.6).
    displayName: Version of PostgreSQL Image
    name: IMAGE_STREAM_VERSION
    required: true
    value: centos7-12.4-3.0-4.5.0
  - description: Storage class for PVCs.
    displayName: Storage class for PVCs.
    name: STORAGE_CLASS
    value: gluster-file-db
objects:
  - apiVersion: v1
    data:
      setup.sql: |-
        SET application_name="container_setup";

        create extension postgis;
        create extension postgis_topology;
        create extension fuzzystrmatch;
        create extension postgis_tiger_geocoder;
        create extension pg_stat_statements;
        create extension pgaudit;
        create extension plr;
        create extension "uuid-ossp";

        alter user postgres password 'PG_ROOT_PASSWORD'; -- these values are automatically replaced by secrets

        create user "PG_PRIMARY_USER" with REPLICATION  PASSWORD 'PG_PRIMARY_PASSWORD';
        create user "PG_USER" with password 'PG_PASSWORD';

        -- read only account for generating tiles
        create user ftw_reader with password 'PG_PASSWORD';

        create table primarytable (key varchar(20), value varchar(20));
        grant all on primarytable to "PG_PRIMARY_USER";

        create database "PG_DATABASE";

        grant all privileges on database "PG_DATABASE" to "PG_USER";


        \c "PG_DATABASE"

        create extension postgis;
        create extension postgis_topology;
        create extension fuzzystrmatch;
        create extension postgis_tiger_geocoder;
        create extension pg_stat_statements;
        create extension pgaudit;
        create extension plr;
        create extension "uuid-ossp";

        \c "PG_DATABASE" "PG_USER";

        create table testtable (
          name varchar(30) primary key,
          value varchar(50) not null,
          updatedt timestamp not null
        );

        insert into testtable (name, value, updatedt) values ('CPU', '256', now());
        insert into testtable (name, value, updatedt) values ('MEM', '512m', now());

        grant all on testtable to "PG_PRIMARY_USER";

        create schema postgis_ftw;
        grant usage on schema postgis_ftw to ftw_reader;
        ALTER DEFAULT PRIVILEGES IN SCHEMA postgis_ftw GRANT SELECT ON TABLES TO ftw_reader;

    kind: ConfigMap
    metadata:
      labels:
        app: ${REPO}-${ZONE}
        name: ${REPO}-${ZONE}-${COMPONENT}-setupcfg
        appver: ${REPO}-${ZONE}-${COMPONENT}
      name: ${REPO}-${ZONE}-${COMPONENT}-setupcfg
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${REPO}-${ZONE}
      annotations:
        template.openshift.io/expose-uri: postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="postgresql")].port}
      name: ${REPO}-${ZONE}-${COMPONENT}
    spec:
      ports:
        - name: postgresql
          nodePort: 0
          port: 5432
          protocol: TCP
          targetPort: 5432
      selector:
        name: ${REPO}-${ZONE}-${COMPONENT}
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ${REPO}-${ZONE}-${COMPONENT}
      labels:
        app: ${REPO}-${ZONE}
      annotations:
        template.openshift.io.bcgov/create: "true"
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: ${VOLUME_CAPACITY}
      storageClassName: ${STORAGE_CLASS}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        template.alpha.openshift.io/wait-for-ready: "true"
      name: ${REPO}-${ZONE}-${COMPONENT}
      labels:
        app: ${REPO}-${ZONE}
    spec:
      replicas: 1
      selector:
        matchLabels:
          deployment: ${REPO}-${ZONE}-${COMPONENT}
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            name: ${REPO}-${ZONE}-${COMPONENT}
            appver: ${REPO}-${ZONE}
            deployment: ${REPO}-${ZONE}-${COMPONENT}
        spec:
          containers:
            - capabilities: {}
              env:
                - name: PG_PRIMARY_PORT
                  value: "5432"
                - name: CONTAINER_NAME
                  value: ${REPO}-${ZONE}-${COMPONENT}
                - name: PG_PRIMARY_HOST
                  value: ${REPO}-${ZONE}-${COMPONENT}
                - name: PGDATA_PATH_OVERRIDE
                  value: userdata
                - name: PGHOST
                  value: /tmp
                - name: PG_DATABASE
                  valueFrom:
                    secretKeyRef:
                        key: database-name
                        name: ${REPO}-${ZONE}-${COMPONENT}
                - name: PG_PASSWORD
                  valueFrom:
                    secretKeyRef:
                        key: database-password
                        name: ${REPO}-${ZONE}-${COMPONENT}
                - name: PG_USER
                  valueFrom:
                    secretKeyRef:
                        key: database-user
                        name: ${REPO}-${ZONE}-${COMPONENT}
                - name: PG_MODE
                  valueFrom:
                    secretKeyRef:
                        key: PG_MODE
                        name: ${REPO}-${ZONE}-crunchy-db-credentials
                - name: PG_PRIMARY_PASSWORD
                  valueFrom:
                    secretKeyRef:
                        key: PG_PRIMARY_PASSWORD
                        name: ${REPO}-${ZONE}-crunchy-db-credentials
                - name: PG_PRIMARY_USER
                  valueFrom:
                    secretKeyRef:
                        key: PG_PRIMARY_USER
                        name: ${REPO}-${ZONE}-crunchy-db-credentials
                - name: PG_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                        key: PG_ROOT_PASSWORD
                        name: ${REPO}-${ZONE}-crunchy-db-credentials
              image: "ghcr.io/bcgov/${REPO}/${COMPONENT}:${TAG}"
              imagePullPolicy: IfNotPresent
              livenessProbe:
                failureThreshold: 3
                initialDelaySeconds: 30
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 5432
                timeoutSeconds: 1
              name: ${REPO}-${ZONE}-${COMPONENT}
              ports:
                - containerPort: 5432
                  protocol: TCP
              readinessProbe:
                exec:
                  command:
                    - /usr/bin/env
                    - bash
                    - '-c'
                    - >-
                      psql -q -d
                      $PG_DATABASE -c 'SELECT 1'
                initialDelaySeconds: 60
                periodSeconds: 15
                successThreshold: 1
                failureThreshold: 5
                timeoutSeconds: 5
              resources:
                requests:
                  cpu: ${REQUEST_CPU}
                  memory: ${REQUEST_MEMORY}
                limits:
                  cpu: ${LIMIT_CPU}
                  memory: ${LIMIT_MEMORY}
              securityContext:
                capabilities: {}
                privileged: false
              terminationMessagePath: /dev/termination-log
              volumeMounts:
                - mountPath: /pgdata
                  name: ${REPO}-${ZONE}-${COMPONENT}-data
                - mountPath: /var/run/postgresql
                  name: ${REPO}-${ZONE}-${COMPONENT}-run
                - mountPath: /pgconf
                  name: ${REPO}-${ZONE}-${COMPONENT}-setupcfg
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          volumes:
            - name: ${REPO}-${ZONE}-${COMPONENT}-data
              persistentVolumeClaim:
                claimName: ${REPO}-${ZONE}-${COMPONENT}
            - name: ${REPO}-${ZONE}-${COMPONENT}-run
              emptyDir: {}
            - configMap:
                name: ${REPO}-${ZONE}-${COMPONENT}-setupcfg
              name: ${REPO}-${ZONE}-${COMPONENT}-setupcfg
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: ${REPO}-${ZONE}-${COMPONENT}-network-policy
      labels:
        app: ${REPO}-${ZONE}
    spec:
      podSelector:
        matchLabels:
          name: ${REPO}-${ZONE}-${COMPONENT}
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  name: ${REPO}-${ZONE}-backend
          ports:
            - protocol: TCP
              port: 5432
      policyTypes:
        - Ingress
