---
apiVersion: v1
kind: Template
metadata:
  annotations:
    description: "Minio deployment"
  labels:
    app: "gwells${NAME_SUFFIX}"
    template: "gwells-minio-template${NAME_SUFFIX}"
  name: "gwells-minio${NAME_SUFFIX}"
parameters:
  - name: "NAME_SUFFIX"
    required: true
  - name: "SECRETS"
    displayName: "Secret object to reference"
    value: "gwells-minio-secrets"
  - name: "SRC_NAMESPACE"
    displayName: "Namespace containing the deployment source"
    value: "26e83e-tools"
  - name: "SRC_IMAGE"
    displayName: "Name of source image"
    value: "gwells-minio"
  - name: "SRC_TAG"
    displayName: "Tag of source image"
    value: "latest"
  - name: "DEST_PVC_SIZE"
    displayName: "PVC size"
    value: "1Gi"
  - name: "DEST_PVC_CLASS"
    displayName: "PVC class"
    value: "netapp-file-standard"
  - name: "DEST_PVC_ACCESS"
    displayName: "PVC access mode"
    value: "ReadWriteMany"
  - name: "HOSTNAME"
    displayName: "Hostname for Minio service"
    required: true
objects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      finalizers:
      - kubernetes.io/pvc-protection
      name: "gwells-minio${NAME_SUFFIX}"
      labels:
        app: "gwells${NAME_SUFFIX}"
        name: gwells-minio${NAME_SUFFIX}
    spec:
      accessModes:
      - ${DEST_PVC_ACCESS}
      resources:
        requests:
          storage: ${DEST_PVC_SIZE}
      storageClassName: ${DEST_PVC_CLASS}
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: "gwells${NAME_SUFFIX}"
        name: "gwells-minio${NAME_SUFFIX}"
      name: "gwells-minio${NAME_SUFFIX}"
    spec:
      replicas: 1
      strategy:
        activeDeadlineSeconds: 3000
        recreateParams:
          timeoutSeconds: 600
        type: Recreate
      template:
        metadata:
          labels:
            app: "gwells${NAME_SUFFIX}"
            name: gwells-minio${NAME_SUFFIX}
        spec:
          containers:
          - env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: ${SECRETS}
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ${SECRETS}
                  key: MINIO_SECRET_KEY
            - name: MINIO_DATA_DIR
              value: /opt/minio/s3/data
            image: image-registry.openshift-image-registry.svc:5000/${SRC_NAMESPACE}/${SRC_IMAGE}:${SRC_TAG}
            imagePullPolicy: Always
            name: "gwells-minio${NAME_SUFFIX}"
            command:
              - '/bin/sh'
              - '-c'
            args:
              - '/minio-entrypoint.sh server /opt/minio/s3/data'
            ports:
            - containerPort: 9000
              protocol: TCP
            resources:
              limits:
                cpu: 250m
              requests:
                cpu: 100m
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /opt/minio/s3/data
              name: minio-vol
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          volumes:
          - name: minio-vol
            persistentVolumeClaim:
              claimName: "gwells-minio${NAME_SUFFIX}"
      triggers:
      - type: ConfigChange
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: gwells${NAME_SUFFIX}
        name: gwells-minio${NAME_SUFFIX}
      name: gwells-minio${NAME_SUFFIX}
    spec:
      selector:
        app: gwells${NAME_SUFFIX}
        name: gwells-minio${NAME_SUFFIX}
      ports:
      - name: 9000-tcp
        port: 9000
        protocol: TCP
        targetPort: 9000
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: gwells${NAME_SUFFIX}
        name: gwells-minio${NAME_SUFFIX}
      name: gwells-minio${NAME_SUFFIX}
    spec:
      host: ${HOSTNAME}
      port:
        targetPort: 9000-tcp
      to:
        kind: Service
        name: gwells-minio${NAME_SUFFIX}
        weight: 100
      wildcardPolicy: None
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
