---
apiVersion: v1
kind: Template
metadata:
  annotations:
    description: "Scheduled Task to perform a folder backup"
    tags: "cronjob,backup"
  labels:
    app: ${SOURCE_PVC}-backup-folder
    cronjob: ${SOURCE_PVC}-backup-folder
    template: "${JOB_NAME}-backup-folder-template"
  name: "${JOB_NAME}-backup-folder-template"
parameters:
  - name: "SOURCE_PVC"
    displayName: "PVC to backup"
    description: "The name of the PVC to be backed up."
    required: true
  - name: "JOB_NAME"
    displayName: "Job Name"
    description: "Name of the Scheduled Job to Create."
    value: "pvc-backup"
    required: true
  - name: "SCHEDULE"
    displayName: "Cron Schedule"
    description: "Cron Schedule to Execute the Job (in UTC)"
    # 12:00 UTC = 4:00 AM PDT
    value: "0 12 * * *"
    required: true
  - name: "DEST_PVC_SIZE"
    displayName: "PVC size"
    description: "The size of the PVC to create."
    required: false
    value: "10Gi"
  - name: "DEST_PVC_CLASS"
    displayName: "PVC class"
    description: "The class of PVC to create."
    required: false
    value: "gluster-file"
  - name: "DEST_PVC_ACCESS"
    displayName: "PVC access mode"
    description: "The access mode of the PVC to create."
    required: false
    value: "ReadWriteOnce"
  - name: "SOURCE_IMAGE_NAME"
    displayName: "Source image Name"
    description: "The name of the image to use for this resource."
    required: true
    value: "backup-pvc"
  - name: "SOURCE_IMAGE_TAG"
    displayName: "Source image tag"
    description: "The name of the image tag to use for this resource."
    required: true
    value: "latest"
  - name: "IMAGE_NAMESPACE"
    displayName: "Image Namespace"
    description: "The namespace of the OpenShift project containing the imagestream for the application."
    required: true
    value: "moe-gwells-tools"
  - name: "SUCCESS_JOBS_HISTORY_LIMIT"
    displayName: "Successful Job History Limit"
    description: "The number of successful jobs that will be retained."
    value: "5"
    required: true
  - name: "FAILED_JOBS_HISTORY_LIMIT"
    displayName: "Failed Job History Limit"
    description: "The number of failed jobs that will be retained."
    value: "2"
    required: true
  - name: "JOB_BACKOFF_LIMIT"
    displayName: "Job Backoff Limit"
    description: "The number of attempts to try for a successful job outcome."
    value: "0"
    required: true
  - name: "JOB_DEADLINE_SECONDS"
    displayName: "Job deadline (seconds)"
    description: "The maximum amount of time to let this job run."
    value: "600"
    required: true
objects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      finalizers:
      - kubernetes.io/pvc-protection
      labels:
        app: ${SOURCE_PVC}-backup
        cronjob: ${SOURCE_PVC}-backup
        template: "${JOB_NAME}-config-template"
      name: ${SOURCE_PVC}-backup
    spec:
      accessModes:
      - ${DEST_PVC_ACCESS}
      resources:
        requests:
          storage: ${DEST_PVC_SIZE}
      storageClassName: ${DEST_PVC_CLASS}
  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: ${SOURCE_PVC}-backup
    spec:
      concurrencyPolicy: Forbid
      failedJobsHistoryLimit: ${{FAILED_JOBS_HISTORY_LIMIT}}
      jobTemplate:
        metadata:
          labels:
            app: ${SOURCE_PVC}-backup
            cronjob: ${SOURCE_PVC}-backup
            template: "${JOB_NAME}-config-template"
        spec:
          backoffLimit: ${{JOB_BACKOFF_LIMIT}}
          template:
            spec:
              activeDeadlineSeconds: ${{JOB_DEADLINE_SECONDS}}
              containers:
              - command:
                - /bin/sh
                - -c
                - /entrypoint.sh
                image: docker-registry.default.svc:5000/${IMAGE_NAMESPACE}/${SOURCE_IMAGE_NAME}:${SOURCE_IMAGE_TAG}
                imagePullPolicy: Always
                name: backup-cronjob
                terminationMessagePath: /dev/termination-log
                terminationMessagePolicy: File
                volumeMounts:
                - mountPath: /mnt/dest/
                  name: ${JOB_NAME}
                - mountPath: /mnt/src/
                  name: ${SOURCE_PVC}
                  readOnly: true
              dnsPolicy: ClusterFirst
              restartPolicy: Never
              schedulerName: default-scheduler
              terminationGracePeriodSeconds: 30
              volumes:
              - name: ${JOB_NAME}
                persistentVolumeClaim:
                  claimName: ${SOURCE_PVC}-backup
              - name: ${SOURCE_PVC}
                persistentVolumeClaim:
                  claimName: ${SOURCE_PVC}
      schedule: ${SCHEDULE}
      successfulJobsHistoryLimit: ${{SUCCESS_JOBS_HISTORY_LIMIT}}
