# Copyright 2021 The Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: |
      Deployment template for the GWELLS OCP3 to OCP4 reverse proxy.
  name: gwells-maintenance${NAME_SUFFIX}
objects:
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: gwells${NAME_SUFFIX}
        name: gwells-maintenance${NAME_SUFFIX}
      name: gwells-maintenance${NAME_SUFFIX}
    spec:
      host: ${SOURCE_HOST_NAME}
      port:
        targetPort: 2015-tcp
      tls:
        termination: edge
      to:
        kind: Service
        name: gwells-maintenance${NAME_SUFFIX}
        weight: 100
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: gwells-maintenance${NAME_SUFFIX}-config
      labels:
        app: gwells${NAME_SUFFIX}
        name: gwells-maintenance${NAME_SUFFIX}-config
    data:
      Caddyfile: |
        :2015 {
             reverse_proxy * https://${DESTINATION_HOST_NAME} {
                header_up Host {http.reverse_proxy.upstream.hostport}
                header_up X-Real-IP {remote_host}
                header_up X-Forwarded-For {remote_host}
                header_up X-Forwarded-Proto {scheme}
                #header_up Connection {>Connection}
                #header_up Upgrade {>Upgrade}
                flush_interval -1
            }

            log {
                # errors stdout
                output stdout 
                #format single_field common_log
          }
        }

        :2016 {
            respond /health 200
            
            log {
              # errors stdout
              output discard 
              #format single_field common_log
          }
        }
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: gwells${NAME_SUFFIX}
        name: gwells-maintenance${NAME_SUFFIX}
      name: gwells-maintenance${NAME_SUFFIX}
    spec:
      selector:
        role: proxy
        name: gwells-maintenance${NAME_SUFFIX}
      ports:
        - name: 2015-tcp
          port: 2015
          protocol: TCP
          targetPort: 2015
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: gwells${NAME_SUFFIX}
        name: gwells-maintenance${NAME_SUFFIX}
      name: gwells-maintenance${NAME_SUFFIX}
    spec:
      strategy:
        type: Rolling
      triggers:
        - type: ConfigChange
      replicas: ${{REPLICA_COUNT}}
      selector:
        role: proxy
        name: gwells-maintenance${NAME_SUFFIX}
      template:
        metadata:
          labels:
            app: gwells${NAME_SUFFIX}
            role: proxy
            name: gwells-maintenance${NAME_SUFFIX}
          name: gwells-maintenance${NAME_SUFFIX}
        spec:
          containers:
            - name: gwells-maintenance${NAME_SUFFIX}
              imagePullPolicy: Always
              image: "docker-registry.default.svc:5000/moe-gwells-tools/caddy:2"
              env:
                - name: XDG_DATA_HOME
                  value: /tmp
              livenessProbe:
                httpGet:
                  path: /health
                  port: 2016
                  scheme: HTTP
                failureThreshold: 5
                periodSeconds: 3
              readinessProbe:
                httpGet:
                  path: /health
                  port: 2016
                timeoutSeconds: 10
              ports:
                - containerPort: 2015
              resources:
                limits:
                  cpu: 100m
                  memory: 92Mi
                requests:
                  cpu: 30m
                  memory: 48Mi
              volumeMounts:
                - name: config-vol
                  mountPath: /etc/caddy/Caddyfile
                  subPath: Caddyfile
          volumes:
            - name: config-vol
              configMap:
                name: gwells-maintenance${NAME_SUFFIX}-config
parameters:
  - displayName: Name
    name: NAME_SUFFIX
    required: true
  - name: DESTINATION_HOST_NAME
    description:
      The destination address that is being proxied.
    displayName: Redirect Destination
    required: true
  - name: SOURCE_HOST_NAME
    description: |
      The route that will be redirected to the destination URL.
    displayName: Front Door Route
    required: true
  - name: REPLICA_COUNT
    description: The number of PROXY pods to start
    displayName: Replica Count
    value: "2"
  # - name: PROXY_MIN_HPA
  #   description: Min Number of PROXY pods for HPA
  #   displayName: PROXY Min HPA
  #   value: 3
  # - name: PROXY_MAX_HPA
  #   description: Max Number of PROXY pods for HPA
  #   displayName: PROXY Max HPA
  #   value: 9