apiVersion: v1
kind: Template
metadata: {}
parameters:
  - name: VERSION
    value: v1.0.0
  - name: NAMESPACE
    value: moe-gwells-tools
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      creationTimestamp: null
      labels:
        name: gwells-documents-backup
        component: backups
        part-of: gwells
      name: gwells-documents-backup
      namespace: "${NAMESPACE}"
    spec:
      lookupPolicy:
        local: false
    status:
      dockerImageRepository: ""
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      creationTimestamp: null
      labels:
        name: "gwells-documents-backup-${VERSION}"
        component: backups
        version: ${VERSION}
        part-of: gwells
      name: "gwells-documents-backup-${VERSION}"
      namespace: "${NAMESPACE}"
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: gwells-documents-backup:${VERSION}
      postCommit: {}
      resources: {}
      source:
        git:
          uri: https://github.com/bcgov/gwells.git
          ref: steve/backups
        contextDir: openshift/ocp4/jobs/minio-backup
        dockerfile: |
          FROM alpine:latest
          USER root
          RUN apk add --update \
              curl rsync \
              && rm -rf /var/cache/apk/*
          RUN curl -Lo restic.bz2 https://github.com/restic/restic/releases/download/v0.9.4/restic_0.9.4_linux_amd64.bz2 \
              && bzip2 -d restic.bz2 \
              && mv restic /usr/bin/restic \
              && chmod +x /usr/bin/restic
          COPY ./entrypoint.sh /
          ENTRYPOINT ["/entrypoint.sh"]
          USER 1001
        type: Dockerfile
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: alpine:3.7
            namespace: openshift
        type: Docker
      triggers:
      - type: ConfigChange
    status:
      lastVersion: 0
