apiVersion: v1
kind: Template
metadata: {}
parameters:
  - name: NAME_SUFFIX
    required: true
  - name: NAMESPACE
    required: true
  - name: PVC_SIZE
    value: "15Gi"
  - name: DEST_PVC
    required: true
  - name: VERSION
    value: v1.0.0
  - name: SCHEDULE
    value: "15 3 * * *"
    required: false
  - name: SOURCE_PVC
    required: true
objects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      finalizers:
      - kubernetes.io/pvc-protection
      name: "gwells-documents-${NAME_SUFFIX}-backup-vol"
      labels:
        app: "gwells-${NAME_SUFFIX}"
        name: "gwells-${NAME_SUFFIX}-documents-backup"
        component: backups
        part-of: gwells
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: ${PVC_SIZE}
      storageClassName: gluster-file
  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: gwells-documents-${NAME_SUFFIX}-backup
      namespace: "${NAMESPACE}"
    spec:
      concurrencyPolicy: Forbid
      failedJobsHistoryLimit: 3
      jobTemplate:
        metadata:
          labels:
            app: "gwells-${NAME_SUFFIX}"
            name: "gwells-${NAME_SUFFIX}-documents-backup"
            component: backups
            part-of: gwells
        spec:
          backoffLimit: 10
          template:
            spec:
              activeDeadlineSeconds: 3600
              containers:
              - image: docker-registry.default.svc:5000/${NAMESPACE}/gwells-documents-backup:${VERSION}
                imagePullPolicy: Always
                name: minio-backup
                env:
                  - name: RESTIC_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        key: RESTIC_PASSWORD
                        name: minio-access-parameters-${NAME_SUFFIX}
                volumeMounts:
                - mountPath: /mnt/dest/
                  name: dest
                - mountPath: /backup
                  name: backup          
                - mountPath: /mnt/source/
                  name: source
                  readOnly: true
              restartPolicy: OnFailure
              terminationGracePeriodSeconds: 30
              volumes:
              - name: source
                persistentVolumeClaim:
                  claimName: "${SOURCE_PVC}"
              - name: dest
                persistentVolumeClaim:
                  claimName: "${DEST_PVC}"
              - name: backup
                persistentVolumeClaim:
                  claimName: "gwells-documents-${NAME_SUFFIX}-backup-vol"
      schedule: ${SCHEDULE}
      successfulJobsHistoryLimit: 3
