---
apiVersion: v1
kind: Template
parameters:
  # - name: "NAME"
  #   displayName: "App to deploy"
  #   value: "minio"
  # - name: "SECRETS"
  #   displayName: "Secret object to reference"
  #   value: "minio-secrets"
  - name: "SRC_NAMESPACE"
    displayName: "Namespace containing the deployment source"
    value: "moe-gwells-tools"
  - name: "SRC_IMAGE"
    displayName: "Name of source image"
    value: "minio"
  # - name: "SRC_TAG"
  #   displayName: "Tag of source image"
    #value: "latest"
  - name: "DEST_PVC_SIZE"
    displayName: "PVC size"
    value: "100Mi"
  # - name: "DEST_PVC_CLASS"
  #   displayName: "PVC class"
  #   value: "gluster-file"
  # - name: "DEST_PVC_ACCESS"
  #   displayName: "PVC access mode"
  #   value: "ReadWriteOnce"
  - name: "IMAGE_TAG"
    required: true
  - name: "MINIO_DATA_DIR"
    required: true
  - name: "ENV_NAME"
    required: true
  - name: "NAME_SUFFIX"
    required: false
objects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: "minio-config-vol-v2${NAME_SUFFIX}"
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: ${DEST_PVC_SIZE}
      storageClassName: netapp-file-standard
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: "minio-data-vol${NAME_SUFFIX}"
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: ${DEST_PVC_SIZE}
      storageClassName: netapp-file-standard
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: "minio${NAME_SUFFIX}"
        template: "minio${NAME_SUFFIX}-template"
      name: "minio${NAME_SUFFIX}"
    spec:
      replicas: 1
      strategy:
        activeDeadlineSeconds: 3000
        recreateParams:
          timeoutSeconds: 600
        type: Recreate
      template:
        metadata:
          labels:
            app: "minio${NAME_SUFFIX}"
            template: "minio${NAME_SUFFIX}-template"
        spec:
          containers:
          - env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio${NAME_SUFFIX}
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio${NAME_SUFFIX}
                  key: MINIO_SECRET_KEY
            - name: MINIO_DATA_DIR
              value: /opt/minio/s3/data
            - name: MINIO_CONFIG_DIR
              value: /opt/minio/s3/config
            image: ghcr.io/bcgov/nr-gwells/minio:${IMAGE_TAG}
            imagePullPolicy: Always
            name: "minio${NAME_SUFFIX}"
            ports:
            - containerPort: 9000
              protocol: TCP
            resources:
              limits:
                cpu: 100m
              requests:
                cpu: 50m
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /opt/minio/s3/config
              name: config-vol
            - mountPath: /opt/minio/s3/data
              name: data-vol
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          volumes:
          - name: config-vol
            persistentVolumeClaim:
              claimName: "minio-config-vol-v2${NAME_SUFFIX}"
          - name: data-vol
            persistentVolumeClaim:
              claimName: "minio-data-vol${NAME_SUFFIX}"
      triggers:
      - type: ConfigChange
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: "minio${NAME_SUFFIX}"
      name: "minio${NAME_SUFFIX}"
    spec:
      ports:
      - name: 9000-tcp
        port: 9000
        protocol: TCP
        targetPort: 9000
