kind: Template
apiVersion: template.openshift.io/v1
metadata:
  annotations:
    description: "Minio deployment"
  labels:
    app: "${NAME}"
    template: "${NAME}-template"
  name: "${NAME}"
parameters:
  - name: "NAME"
    displayName: "App to deploy"
    value: "minio"
  # - name: "SECRETS"
  #   displayName: "Secret object to reference"
  #   value: "minio-secrets"
  - name: "SRC_NAMESPACE"
    displayName: "Namespace containing the deployment source"
    value: "moe-gwells-tools"
  - name: "SRC_IMAGE"
    displayName: "Name of source image"
    value: "minio"
  # - name: "SRC_TAG"
  #   displayName: "Tag of source image"
    #value: "latest"
  - name: "DEST_PVC_SIZE"
    displayName: "PVC size"
    value: "100Mi"
  # - name: "DEST_PVC_CLASS"
  #   displayName: "PVC class"
  #   value: "gluster-file"
  - name: "DEST_PVC_ACCESS"
    displayName: "PVC access mode"
    value: "ReadWriteOnce"
  - name: "IMAGE_TAG"
    required: true
  - name: "MINIO_DATA_DIR"
    required: true
  - name: "ENV_NAME"
    required: true
  - name: "NAME_SUFFIX"
    required: false
objects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      finalizers:
      - kubernetes.io/pvc-protection
      name: "gwells${NAME_SUFFIX}-minio-config-vol-v2"
      labels:
        app: "gwells${NAME_SUFFIX}-minio"
    spec:
      accessModes:
      - ${DEST_PVC_ACCESS}
      resources:
        requests:
          storage: ${DEST_PVC_SIZE}
      storageClassName: netapp-file-standard
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      finalizers:
      - kubernetes.io/pvc-protection
      name: "gwells${NAME_SUFFIX}-minio-data-vol"
      labels:
        app: "gwells${NAME_SUFFIX}-minio"
    spec:
      accessModes:
      - ${DEST_PVC_ACCESS}
      resources:
        requests:
          storage: ${DEST_PVC_SIZE}
      storageClassName: netapp-file-standard
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: "gwells${NAME_SUFFIX}-minio"
      name: "gwells${NAME_SUFFIX}-minio"
    spec:
      replicas: 1
      selector:
        matchLabels:
          deployment: "gwells${NAME_SUFFIX}-minio"
      strategy:
        activeDeadlineSeconds: 3000
        recreateParams:
          timeoutSeconds: 600
        type: Recreate
      template:
        metadata:
          labels:
            name: "gwells${NAME_SUFFIX}-minio"
            deployment: "gwells${NAME_SUFFIX}-minio"
        spec:
          containers:
          - env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: "gwells${NAME_SUFFIX}-minio"
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: "gwells${NAME_SUFFIX}-minio"
                  key: MINIO_SECRET_KEY
            - name: MINIO_DATA_DIR
              value: /opt/minio/s3/data
            - name: MINIO_CONFIG_DIR
              value: /opt/minio/s3/config
            image: ghcr.io/bcgov/nr-gwells/minio:${IMAGE_TAG}
            imagePullPolicy: Always
            name: "gwells${NAME_SUFFIX}-minio"
            ports:
            - containerPort: 9000
              protocol: TCP
            resources:
              limits:
                cpu: 100m
              requests:
                cpu: 75m
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /opt/minio/s3/config
              name: config-vol
            - mountPath: /opt/minio/s3/data
              name: data-vol
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          volumes:
          - name: config-vol
            persistentVolumeClaim:
              claimName: "gwells${NAME_SUFFIX}-minio-config-vol-v2"
          - name: data-vol
            persistentVolumeClaim:
              claimName: "gwells${NAME_SUFFIX}-minio-data-vol"
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: "gwells${NAME_SUFFIX}-minio"
      name: "gwells${NAME_SUFFIX}-minio"
    spec:
      ports:
      - name: 9000-tcp
        port: 9000
        protocol: TCP
        targetPort: 9000
