apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  creationTimestamp: 2019-02-05T18:41:45Z
  labels:
    build: gwells-python
  name: gwells-python
  namespace: 26e83e-tools
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: gwells-python:latest
  postCommit: {}
  resources:
    requests:
      memory: 1Gi
      cpu: 1000m
    limits:
      memory: 4Gi
      cpu: 4000m
  runPolicy: Serial
  source:
    contextDir: openshift/docker/backend
    git:
      ref: release
      uri: https://github.com/bcgov/gwells
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8/python-36:1
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
  - imageChange:
    type: ImageChange
status:
  lastVersion: 1
