name: .Deploys

on:
  workflow_call:
    inputs:
      environment:
        description: GitHub environment; e.g. PR number (omit), TEST or PROD
        required: false
        type: string
      tag: 
        description: Image tag; e.g. PR number or latest
        default: ${{ github.event.number }}
        required: false
        type: string
      target:
        description: Deployment target; e.g. PR number (omit), test or prod
        default: ${{ github.event.number }}
        required: false
        type: string

jobs:
  database:
    name: Database
    # environment: ${{ inputs.environment }}
    runs-on: ubuntu-22.04
    steps:
      # - name: Deploy Frontend
      #   uses: bcgov-nr/action-deployer-openshift@v3.0.0
      #   with:
      #     oc_namespace: ${{ vars.OC_NAMESPACE }}
      #     oc_server: ${{ vars.OC_SERVER }}
      #     oc_token: ${{ secrets.OC_TOKEN }}
      #     file: frontend/openshift.deploy.yml
      #     overwrite: true
      #     parameters:
      #       -p TAG=${{ inputs.tag }} -p TARGET=${{ inputs.target }}

      - name: Database
        uses: bcgov-nr/action-deployer-openshift@v3.0.0
        with:
          oc_namespace: ${{ vars.OC_NAMESPACE }}
          oc_server: ${{ vars.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          file: database/postgresql.dc.yml
          overwrite: true
          parameters:
            -p DATABASE_SERVICE_NAME=nr-gwells-pg12-dev-${{ github.event.number }}
            -p IMAGE_STREAM_NAMESPACE=${{ vars.OC_NAMESPACE }}
            -p IMAGE_STREAM_NAME=crunchy-postgres-gis
            -p NAME_SUFFIX=-dev-${{ github.event.number }}
            -p POSTGRESQL_DATABASE=gwells
            -p VOLUME_CAPACITY=1Gi
            -p STORAGE_CLASS=netapp-file-standard
            -p REQUEST_CPU=200m
            -p REQUEST_MEMORY=512Mi
            -p LIMIT_CPU=500m
            -p LIMIT_MEMORY=1Gi
            -p POSTGRESQL_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}

  backend:
    name: Backend
    # environment: ${{ inputs.environment }}
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy Backend
        uses: bcgov-nr/action-deployer-openshift@v3.0.0
        with:
            oc_namespace: ${{ vars.OC_NAMESPACE }}
            oc_server: ${{ vars.OC_SERVER }}
            oc_token: ${{ secrets.OC_TOKEN }}
            file: backend/openshift.backend.yml
            parameters:
                -p NAME_SUFFIX=-dev-${{ github.event.number }}
                -p ENV_NAME=dev
                -p DJANGO_ADMIN_PASSWORD=${{ secrets.DJANGO_ADMIN_PASSWORD }}
                -p DJANGO_ADMIN_URL=${{ secrets.DJANGO_ADMIN_URL }}
                -p DJANGO_ADMIN_USER=${{ secrets.DJANGO_ADMIN_USER }}
                -p DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
                -p E_LICENSING_AUTH_USERNAME=${{ secrets.E_LICENSING_AUTH_USERNAME }}
                -p E_LICENSING_AUTH_PASSWORD=${{ secrets.E_LICENSING_AUTH_PASSWORD }}
                -p E_LICENSING_URL=${{ vars.E_LICENSING_URL }}
                -p DB_REPLICATE=${{ vars.DB_REPLICATE }}
                -p DJANGO_DEBUG=${{ vars.DJANGO_DEBUG }}
                -p ENABLE_ADDITIONAL_DOCUMENTS=${{ vars.ENABLE_ADDITIONAL_DOCUMENTS }}
                -p S3_PRIVATE_BUCKET=${{ vars.S3_PRIVATE_BUCKET }}
                -p S3_PRIVATE_HOST=${{ vars.S3_PRIVATE_HOST }}
                -p S3_WELL_EXPORT_BUCKET=${{ vars.S3_WELL_EXPORT_BUCKET }}
                -p SSO_AUDIENCE=${{ vars.SSO_AUDIENCE }}
                -p SSO_AUTH_HOST=${{ vars.SSO_AUTH_HOST }}
                -p SSO_CLIENT=${{ vars.SSO_CLIENT }}
                -p SSO_IDP_HINT=${{ vars.SSO_IDP_HINT }}
                -p SSO_PORT=${{ vars.SSO_PORT }}
                -p SSO_PUBKEY=${{ vars.SSO_PUBKEY }}
                -p SSO_REALM=${{ vars.SSO_REALM }}
                -p SSO_TEST_AUDIENCE=${{ vars.SSO_TEST_AUDIENCE }}
                -p SSO_TEST_CLIENT=${{ vars.SSO_TEST_CLIENT }}
                -p GDAL_LIBRARY_PATH=${{ vars.GDAL_LIBRARY_PATH }}
                -p GEOS_LIBRARY_PATH=${{ vars.GEOS_LIBRARY_PATH }}