name: .Tests

on:
  workflow_call:
    inputs:
      ### Required
      target:
        description: PR number, test or prod
        required: true
        type: string

      ### Typical / recommended
      triggers:
        description: Bash array to diff for build triggering; omit to always fire
        required: false
        type: string

env:
  DOMAIN: apps.silver.devops.gov.bc.ca
  PREFIX: ${{ github.event.repository.name }}-${{ inputs.target }}

jobs:
  unit-test:
    name: Unit Tests
    # if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    continue-on-error: true
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.7'

      - name: Install GDAL dependencies
        run: sudo apt update && sudo apt install -y gdal-bin libgdal-dev

      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: Install Numpy
        run: python3 -m pip install numpy

      - name: Install ptvsd
        run: python3 -m pip install ptvsd

      - name: Uninstall setuptool
        run: python3 -m pip install setuptools

      - name: Install Setuptools
        run: python3 -m pip install 'setuptools<58.0'

      - name: Install Dependencies
        run: python3 -m pip install -r requirements.txt --verbose
        working-directory: ./backend

      - name: Run Django Tests
        run: python3 manage.py test
        working-directory: ./backend
        