name: Merge

on:
  push:
    branches: [main]
    paths-ignore:
      - '*.md'
      - '.github/**'
      - '.github/graphics/**'
      - '!.github/workflows/**'
  workflow_dispatch:
    inputs:
      pr_no:
        description: "PR-numbered container set to deploy"
        type: number
        required: true

concurrency:
  # Do not interrupt previous workflows
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  init:
    name: Set Variables
    outputs:
      pr: ${{ steps.pr.outputs.pr }}
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      # Get PR number for squash merges to main
      - name: PR Number
        id: pr
        uses: bcgov-nr/action-get-pr@v0.0.1

  deploys-test:
    name: TEST Deploys (${{ needs.init.outputs.pr }})
    needs: [init]
    secrets: inherit
    uses: ./.github/workflows/.deploy.yml
    with:
      environment: test
      tag: ${{ needs.init.outputs.pr }}
      target: test

  # deploy-prod:
  #   name: Deploy (prod)
  #   needs: [deploy-test, vars]
  #   uses: bcgov/quickstart-openshift-helpers/.github/workflows/.deployer.yml@v0.6.1
  #   secrets:
  #     oc_namespace: ${{ secrets.OC_NAMESPACE }}
  #     oc_token: ${{ secrets.OC_TOKEN }}
  #   with:
  #     environment: prod
  #     params:
  #       --set backend.deploymentStrategy=RollingUpdate
  #       --set frontend.deploymentStrategy=RollingUpdate
  #       --set global.autoscaling=true
  #       --set frontend.pdb.enabled=true
  #       --set backend.pdb.enabled=true
  # promote:
  #   name: Promote Images
  #   needs: [deploy-prod, vars]
  #   runs-on: ubuntu-latest
  #   permissions:
  #     packages: write
  #   strategy:
  #     matrix:
  #       package: [migrations, backend, frontend]
  #   timeout-minutes: 1
  #   steps:
  #     - uses: shrink/actions-docker-registry-tag@v4
  #       with:
  #         registry: ghcr.io
  #         repository: ${{ github.repository }}/${{ matrix.package }}
  #         target: ${{ needs.vars.outputs.pr }}
  #         tags: prod
